### ISSUE TITLE
about the dropout in generator core

### ISSUE THREAD

**Issue by yjmlaile** [tychovdo/RevGAN#1]
I notice that in the training of paired revgan model,  the dropout with probability is 0.5 was used in generator reversible core, which  could make the model irreversible. because in the reverse propagation, the same data as forward propagate was input to F or G function with dropout, and the output would be different from that in the forward propagation.

**Comment by tychovdo** [comment]
You are right. To make the core invertible, both F and G should either use the same dropout mask when performing the forward and inverse function or have dropout turned off completely. Dropout was not used for the experiments in the paper. Also, I will clean the code this week to make sure dropout is not turned off in all cases by default.

**Comment by tychovdo** [comment]
And of course, thanks for the comment.
